# ----------------------------------------
# Spring Boot Core Settings
# ----------------------------------------
spring:
  application:
    name: somba-api

  profiles:
    active: development

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:somba_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:securepassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use "validate" or "none" in production
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # MongoDB Configuration (Localhost)
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:somba_mongo_user}:${MONGO_INITDB_ROOT_PASSWORD:somba_mongo_pass}@localhost:${MONGO_PORT:27017}/${MONGO_DB:somba_catalog}

# Server Configuration
server:
  port: ${APP_PORT:8081}

# ----------------------------------------
# Logging Configuration (Best Practices)
# ----------------------------------------
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.somba: DEBUG  # Customize based on your package structure
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"

# ----------------------------------------
# CORS Configuration
# ----------------------------------------
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  exposed-headers: "Authorization"

# ----------------------------------------
# API Versioning
# ----------------------------------------
api:
  version: ${API_VERSION:v1}
