version: '3.8'

services:

  # PostgreSQL Database
  postgres:
    image: postgres:16.1-alpine
    container_name: somba_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer for DB Management
  adminer:
    image: adminer:latest
    container_name: somba_adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres

  # MongoDB NoSQL Database
  mongodb:
    image: mongo:6.0
    container_name: somba_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

# Docker-Managed Named Volumes
volumes:
  db-data:
  mongo-data:
