name: API CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ '**' ]

concurrency:
  group: ${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  Build_and_Test:

    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '21'
      MAVEN_OPTS: '-Xmx2g'
      SONAR_TOKEN: ${{ secrets.API_SONAR_TOKEN }}
      SONAR_ORGANIZATION: jarhead-killgrave
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_PROJECT_KEY: com.somba:api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin
            !~/.m2/repository/org/jacoco
          key: ${{ runner.os }}-maven-${{ hashFiles('**/app/api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Maven Installation
        run: mvn --version
        working-directory: ./app/api

      - name: Build and Test with Maven
        run: mvn clean verify --fail-fast -Dspring.profiles.active=test
        working-directory: ./app/api
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/somba_test_db
          SPRING_DATA_MONGODB_URI: mongodb://test_mongo_user:test_mongo_pass@localhost:27017/test_somba_catalog
          APP_PORT: 8082
          DB_PORT: 5432
          DB_NAME: somba_test_db
          DB_USER: test_user
          DB_PASSWORD: test_password
          MONGO_PORT: 27017
          MONGO_DB: test_somba_catalog
          MONGO_INITDB_ROOT_USERNAME: test_mongo_user
          MONGO_INITDB_ROOT_PASSWORD: test_mongo_pass
          API_VERSION: test_v1

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.login=${{ env.SONAR_TOKEN }}
            -Dsonar.java.binaries=target/classes
          projectBaseDir: ./app/api


      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./app/api/target/surefire-reports/

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ./app/api/target/site/jacoco/
